---
title: "Term Project"
author: "Riley Adams"
date: "9th July, 2022"
output: bookdown::html_document2
bibliography: finalref.bib
---

```{r, echo=FALSE, eval=FALSE}
# setwd("I:/My Drive/Spring 2022/MAT 124/final/MAT124_Final")
```

```{css, echo =FALSE}

h1.title {
  font-size: 38px;
  color: SteelBlue;
  text-align: center;
}
h4.author { 
    font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: black;
  text-align: center;
}
h4.date { 
  font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: black;
  text-align: center;
}
</style>
```

# <span style="color: SteelBlue;"> Introduction </span>{#intro}

You have probably heard of a "Staph Infection", but why is this seemingly common bacterial skin infection becoming a much bigger deal? The simple answer is that the bacteria which causes these skin infections, *Staphylococcus aureus*, has been evolving to develop resistance against the antibiotics which are used to treat it. [@whatsMRSA] This new distinct type of *S. aureus* has been deemed Methicillin-resistant *Staphylococcus aureus*, commonly referred to as MRSA. MRSA first started appearing in healthcare settings, where it caused mortality for hospitalized individuals. However, in the early 1990's a biologically distinct type of MRSA began breaking out in the the greater community, causing severe infections and even mortality among individuals who did not exhibit ill health or risk factors associated with early death. [@LAjail]

# <span style="color: SteelBlue;"> Midterm 1: Compartment Model Analysis </span> {#mt1}



## <span style="color: SteelBlue;"> Introduction: Midterm 1 </span> {#introMT1}



## <span style="color: SteelBlue;"> Results: Midterm 1 </span>{#resMT1}



## <span style="color: SteelBlue;"> Discussion: Midterm 1 </span> {#discMT1}



# <span style="color: SteelBlue;"> Midterm 2: Evolutionary Analysis </span> {#mt2}



## <span style="color: SteelBlue;"> Introduction: Midterm 2 </span> {#introMT2}



## <span style="color: SteelBlue;"> Results: Midterm 2 </span> {#resMT2}



## <span style="color: SteelBlue;"> Discussion: Midterm 2 </span> {#discMT2}



# <span style="color: SteelBlue;"> Final: 3D Protein Structure </span>



# <span style="color: SteelBlue;"> References </span>

